ami                        = " ami-02a39bdb8e8ee056a"
instance_type              = "t2.micro"
keyname                    = "testkey"
name                       = "Consul"
subnet_id                  = "subnet-1da9c855"
Env                        = "dev"
Created_by                 = "ahmed"
Dept                       = "IT"
count                      = 1